apiVersion: apps/v1
{{- $kind := .Values.kind | default "Deployment" }}
kind: {{ $kind }}
metadata:
  name: {{ include "s3-nginx-proxy-chart.fullname" . }}
  labels:
    {{- include "s3-nginx-proxy-chart.labels" . | nindent 4 }}
spec:
  {{- if and (eq $kind "Deployment") (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "s3-nginx-proxy-chart.selectorLabels" . | nindent 6 }}
  {{- if eq $kind "Deployment"}}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- else }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "s3-nginx-proxy-chart.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "s3-nginx-proxy-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3-nginx-proxy-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: entrypoint-scripts
          configMap:
            name: {{ include "s3-nginx-proxy-chart.fullname" . }}-entrypoint-scripts
        - name: secrets
          secret:
            secretName: {{ include "s3-nginx-proxy-chart.fullname" . }}
        - name: nginx-confd
          emptyDir:
            sizeLimit: 10Mi
      {{- if not (and (eq .Values.kind "StatefulSet") (eq .Values.cache.volumeType "pvc")) }}
        - name: nginx-cache
          {{- if eq .Values.cache.volumeType "hostPath" }}
          hostPath:
            path: {{ required "cache.hostPath is missing" .Values.cache.hostPath }}
          {{- else if eq .Values.cache.volumeType "pvc" }}
          {{- if not (eq .Values.kind "StatefulSet") }}
          persistentVolumeClaim:
            claimName: {{ include "s3-nginx-proxy-chart.fullname" . }}
          {{- end }}
          {{- else }}
          emptyDir:
            {{- with .Values.cache.medium }}
            medium: {{ . }}
            {{- end }}
            {{- with .Values.cache.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
          {{- end }}
      {{- else }}
      volumeClaimTemplates:
        - metadata:
            name: nginx-cache
          spec:
            resources:
              requests:
                storage: {{ .Values.cache.sizeLimit }}
            volumeMode: Filesystem
            accessModes:
              {{- toYaml .Values.cache.accessModes | nindent 14 }}
            {{- with .Values.cache.storageClassName }}
            storageClassName: {{ . }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              port: {{ .Values.metrics.enabled | ternary .Values.metrics.port 80 }}
              path: {{ .Values.metrics.enabled | ternary .Values.metrics.location "/" }}
          readinessProbe:
            httpGet:
              port: {{ .Values.metrics.enabled | ternary .Values.metrics.port 80 }}
              path: {{ .Values.metrics.enabled | ternary .Values.metrics.location "/" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: entrypoint-scripts
              mountPath: /docker-entrypoint.d
            - name: secrets
              mountPath: /etc/proxy-config
            - name: nginx-confd
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
        - name: {{ .Chart.Name }}-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/srv/config.sh"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: entrypoint-scripts
              mountPath: /docker-entrypoint.d
            - name: secrets
              mountPath: /etc/proxy-config
            - name: nginx-confd
              mountPath: /etc/nginx/conf.d
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
