{{- $config := list
  (dict
    "suffix" ""
  )
  (dict
    "suffix" "-config-validation"
    "annotations" (dict
      "helm.sh/hook" "pre-install,pre-upgrade,pre-rollback"
      "helm.sh/hook-weight" "-10"
      "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded"
    )
  )
-}}
{{- range $config := $config -}}
{{- with $ }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-nginx-proxy-chart.fullname" . }}-entrypoint-scripts{{ $config.suffix }}
  labels:
    {{- include "s3-nginx-proxy-chart.labels" . | nindent 4 }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- toYaml .Values.entrypointScripts | nindent 2 }}
{{- end }}
{{- end }}
