{{- if .Values.serviceAccount.create -}}
{{- $config := list
  (dict
    "suffix" ""
  )
  (dict
    "suffix" "-config-validation"
    "annotations" (dict
      "helm.sh/hook" "pre-install,pre-upgrade,pre-rollback"
      "helm.sh/hook-weight" "-10"
      "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded"
    )
  )
-}}
{{- range $config := $config -}}
{{- with $ }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-nginx-proxy-chart.serviceAccountName" . }}{{ $config.suffix }}
  labels:
    {{- include "s3-nginx-proxy-chart.labels" . | nindent 4 }}
  {{- if or $config.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with $config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
